version: '3.8'

services:
  # Neon Local Proxy Service
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: acquisitions-neon-local
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    restart: unless-stopped
    networks:
      - acquisitions-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -p 5432 -U neon']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: acquisitions-app-dev
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./package-lock.json:/app/package-lock.json:ro
      # Mount logs directory for persistence
      - ./logs:/app/logs
      # Named volume for node_modules to avoid conflicts
      - node_modules:/app/node_modules
    depends_on:
      neon-local:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - acquisitions-network
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3000/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  node_modules:

networks:
  acquisitions-network:
    driver: bridge
