apiVersion: v1
kind: Service
metadata:
  name: devops-kubernetes-api-service
  labels:
    app: devops-kubernetes-api
spec:
  selector:
    app: devops-kubernetes-api
  ports:
    - protocol: TCP
      port: 3000 
      targetPort: 3000 
  type: NodePort 
